backend:
  name: git-gateway
  branch: "48891"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "presidenza"
    label: "Presidenza"
    folder: "_persone"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titolo" }
      - { name: "nome", label: "Nome" }
      - { name: "email", label: "Email", widget: "string" }
      - { name: "foto", label: "URL Foto", widget: "image" }
      - { name: "layout", label: "Layout", default: "pp", widget: "hidden" }
      - { name: "permalink", label: "Permalink", widget: "string" }
      - { name: "lang", label: "Lingua", default: "it" }
      - { name: "ruolo", label: "Ruolo", widget: "string" }
      - { name: "descrizione", label: "Descrizione", widget: "text" }
      - { name: "ref", label: "Ref interno", widget: "string" }
      - { name: "body", label: "Contenuto", widget: "markdown" }
