backend:
  name: git-gateway
  branch: "48891"

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "staff"
    label: "Staff"
    folder: "content/staff"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "usr" }
      - { label: "Titolo Pagina", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }

      - label: "Informazioni Personali"
        name: "person"
        widget: "object"
        fields:
          - { label: "Nome", name: "name", widget: "string" }
          - { label: "Immagine Copertina", name: "image", widget: "image" }
          - { label: "Incarico", name: "incarico", widget: "string" }
          - { label: "Tipo di Incarico", name: "tipo_incarico", widget: "string" default: "interno"}
          - { label: "Data di Insediamento", name: "data_insediamento", widget: "datetime", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY", time_format: false default: "01 gennaio 2025"}
          - { label: "Email", name: "email", widget: "string" }
          - label: "Competenze"
            name: "competenze"
            widget: "list"
            summary: "{{fields}}"
            field: { label: "Competenza", name: "item", widget: "string" }

          - label: "Organizzazioni"
            name: "organizzazione"
            widget: "list"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "text" }

          - label: "Documenti"
            name: "documents"
            widget: "list"
            fields:
              - { label: "Titolo", name: "title", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "string" }
              - { label: "Link al Documento", name: "link", widget: "string" }

      - { label: "Contenuto", name: "body", widget: "markdown" }
